### ISSUE TITLE
Wrong session id

### ISSUE THREAD

**Issue by tsikup** [manilarome/the-glorious-lightdm-webkit2-theme#10]
File: js/sessions-screen.js
Line: 105
Code: `this._defaultSession = lightdm.default_session || this._sessionsObject[0].key;`

I'm using i3 window manager, and although the value of `this._sessionsObject[0].key` is indeed equal to `i3`, `lightdm.default_session` value is equal to `xfce`. Thus the variables `this._defaultSession` in line 105 is `xfce` and `defaultSessionItem` in line 112 is `null`, which breaks the code. 

Edit: typos

**Comment by eromatiya** [comment]
Thanks for reporting it!

> this._defaultSession in line 105 and defaultSessionItem in line 112 are null

Hmm weird. Why would the this._defaultSession variable be null if both lightdm.default_session and this._sessionsObject[0].key have value? I'm pretty new to javascript so maybe I'm missing something. I'll look into it. For now, I'll just switch them so the default would be the first key in the object. Thank you!

**Comment by eromatiya** [comment]
https://github.com/manilarome/the-glorious-lightdm-webkit2-theme/commit/ea7534ffbc3df0b2deccb6623e79e9a06ff49d61 I hope it helps!

**Comment by tsikup** [comment]
Sorry, only the defaultSessionItem is null, because the this._defaultSession is set to xfce, which does not exist in the document dom.

**Comment by eromatiya** [comment]
Thanks for the clarification! Anyway, I think it's better to use the first object instead of `lightdm.default_session`. I don't have an idea why would lightdm set xfce as your default haha.
