### ISSUE TITLE
Le live demo, c'est nonexistent

### ISSUE THREAD

**Issue by boomskats** [manilarome/the-glorious-lightdm-webkit2-theme#11]
Why would you tease us with a link to a live demo that doesn't exist?

Whyyyy?

**Comment by eromatiya** [comment]
Oof sorry. It probably broke because I renamed the repo. Sorry about that.
Will fix later. For now, here's the [updated link](
https://manilarome.github.io/lightdm-webkit2-theme-glorious/).

**Comment by eromatiya** [comment]
Fixed it!

https://github.com/manilarome/lightdm-webkit2-theme-glorious/commit/98a369068732f9d9c11ff96c11cff4af92290919 

Will close this now! :)
