### ISSUE TITLE
Unlock Key Non-Remappable

### ISSUE THREAD

**Issue by Potato-Rocket** [manilarome/the-glorious-lightdm-webkit2-theme#14]
It should be possible to set a different key, like "Return" to open the unlock screen rather than just "Escape". For example, my laptop's escape key is broken so I need an external keybpard to log in.

**Comment by eromatiya** [comment]
I see. That's a nice addition. I'll work into it later or tomorrow, right now you can swipe up to close the 'screens' if your <kbd>Escape</kbd> key is broken.

**Comment by Potato-Rocket** [comment]
Oh wow cool. Also, thanks.

**Comment by eromatiya** [comment]
Hello, I published v1.3. It contains keybindings and you can also remap them in the settings :)
