### ISSUE TITLE
null is not an object

### ISSUE THREAD

**Issue by NoSoyJamie** [manilarome/the-glorious-lightdm-webkit2-theme#17]
Hi, seem to be having an issue loading this theme in arch after following the manual instructions on the readme. Attached is the greeter log that was generated. Wondering if you could take a look into it...

[seat0-greeter.log](https://github.com/manilarome/lightdm-webkit2-theme-glorious/files/4963283/seat0-greeter.log)

**Comment by eromatiya** [comment]
Does this always happen? Can you please try to run `lightdm-webkit2-greeter` in your terminal? This error sometimes happen due to some race conditions, like the theme trying to access the `lightdm` object even though it doesn't exist *yet*. Also, do you have a window manager or desktop environment? Because the null value is `item` which is a session/environment you have.

**Comment by NoSoyJamie** [comment]
Hey sorry it took so long to reply, I'm not the best at remembering to continue conversations..

Seems from boot I can get it to partially work by running the following commands:
`sudo systemctl stop lightdm`
`startx`
and in the resulting terminal that shows up
`lightdm-webkit2-greeter`
after that I'm greeted with a "fully working" version of the theme, the only caveat being that the login function doesn't work. likely because I ran the command as the user

It's especially weird because other themes work just fine, they recognize installed window managers, openbox and windowmaker. This one theme doesnt work, which is a shame because I like its design the most

edit: I'm giving up on this arch system, going to try a fresh install and hope that the issue doesnt pop up again..

**Comment by jfrcom** [comment]
I have the exact same issue. I have to fall back to the default theme to log in. However, when running `lightdm-webkit2-greeter` in a terminal after logging in the theme seems to be working fine.
