### ISSUE TITLE
Unable to change avatar

### ISSUE THREAD

**Issue by jpmvferreira** [manilarome/the-glorious-lightdm-webkit2-theme#23]
I've opened this issue after making a comment on a previously closed issue about the same matter. Here's a screenshot of `mugshot`:
![image](https://user-images.githubusercontent.com/41581666/92594075-2ce03d00-f29a-11ea-8d3d-93893eefc115.png)

And here's a screenshot of `lightdm-webkit2-greeter` being run from my terminal:
![image](https://user-images.githubusercontent.com/41581666/92594164-4f725600-f29a-11ea-9c64-7aa1e5365ca4.png)

**Comment by eromatiya** [comment]
Hey thanks for opening an issue! Uhm can you check your accounts list(user selection) if your profile has an image?

**Comment by jpmvferreira** [comment]
It doesn't.
![image](https://user-images.githubusercontent.com/41581666/92600272-3fab3f80-f2a3-11ea-8380-03d1036527f6.png)

**Comment by eromatiya** [comment]
Weird. Lightdm is responsible for providing the information needed and the theme just "fetches" it so I don't think the theme's the issue here. I also cannot reproduced this. Could you please give me more information? Lightdm and lightdm-webkit2-greeter version? Distro you're using? And please try to use a different image. I also cannot update my profile once because the image is unsupported. Please try using any of the example profile pics in `assets/profiles/.

**Comment by jpmvferreira** [comment]
Ah sorry I completely forgot about that, my system is as follows:
- Distro: Manjaro x86_64
- Kernel: 5.4.62-1
- Display Manager: lightdm 1:1.30.0-4
- Greeter: lightdm-webkit2-greeter 2.2.5-3
- Theme: lightdm-webkit2-theme-glorious 2.0.1-1 (AUR)

Using `mugshot` to pick an avatar from `/usr/share/lightdm-webkit/themes/glorious/assets/profiles` didn't work it still showed the default `avatar.svg` as an avatar.

**Comment by eromatiya** [comment]
What is the output of `feh "/var/lib/AccountsService/icons/$(whoami)"`? And `feh ~/.face`?

**Comment by jpmvferreira** [comment]
The output of `sudo feh "/var/lib/AccountsService/icons/$(whoami)"` is my profile picture, the one I wanted to be, and so is for `feh ~/.face`

**Comment by eromatiya** [comment]
Hmm. Now, please run `lightdm-webkit2-greeter` from your terminal, and assuming debug_mode is enabled in your `lightdm-webkit2-greeter.conf`, right click then inspect element. Go to console then run `console.log(lightdm.users);`. It should return the users object with its properties.

![Untitled](https://user-images.githubusercontent.com/40349590/92666636-61a4d080-f33c-11ea-9467-b03e546d9398.png)

**Comment by jpmvferreira** [comment]
Interesting it says `undefined` when asked for user. I've searched archwiki for this but didn't found anything, it's strange considering I'm logging into my account.

![image](https://user-images.githubusercontent.com/41581666/92717030-835f8100-f357-11ea-8682-f4df74f4bc59.png)

**Comment by eromatiya** [comment]
It has a value. Look at the output below the console.log. Press the arrow to show the object properties. It is undefined because the command runs without a problem.

**Comment by jpmvferreira** [comment]
Oh you're right, here's the output:
![image](https://user-images.githubusercontent.com/41581666/92718940-68424080-f35a-11ea-9df9-ed6aa22f2cc9.png)

It seems like it's not fetching the image, because the real name matches the one I'm using in `mugshot` due to the capital U in Undercover, while my username is only undercover.

**Comment by eromatiya** [comment]
> It seems like it's not fetching the image

Yeah. The image property is null. I can safely say that the theme's not the problem here but the lightdm cannot detect your image.

**Comment by jpmvferreira** [comment]
Alright, I'll look into it, I already did `chmod 755 ~/.face` to ensure that it was readable by all, even when I'm not logged in (which is always the case of course) and I also ran `sudo mugshot` just to see if it works but it doesn't.

I'm closing this issue then, if I can't find a fix for it I just change the default `avatar.svg` or something.

**Comment by eromatiya** [comment]
It's really weird that lightdm can't detect it tho. Also, check your profile image type using `file /var/lib/AccountsService/icons/$(whoami)`. The output should be `PNG image data, 200 x 200, 8-bit/color RGB, non-interlaced`.

> I'm closing this issue then, if I can't find a fix for it I just change the default avatar.svg or something.

Yeah I think that's a quick fix for now.

**Comment by jpmvferreira** [comment]
Found a fix, apparently something happened and `/var/lib/AccountsService/icons/undercover` had the wrong permission scheme, reading wasn't allowed by other users, after doing `sudo chmod 755 /var/lib/AccountsService/icons/undercover` I can now read the file, because it's owned by root, and it shows up in the display manager.

The issue is now officially closed.
Thanks for the help!

**Comment by eromatiya** [comment]
Nice! Good job! Thanks for the info! And no problem!

**Comment by chris-aeviator** [comment]
I'm on the same issue. Strangely, when running `lightdm-webkit2-greeter` from an active (logged in) session, I can successfully see my profile image (png), mugshot has it, but when in the "real" greeter I see the default svg. I've owned the image, set it to 755 and still no chance....any ideas? `console.log(...)` also returns the correct image path.

![image](https://user-images.githubusercontent.com/11522213/115605904-60c91980-a2e3-11eb-83ef-8a1499f70310.png)

### UPDATE:

ok - my issue was that the value for `user_image` inside /etc/lightdm/lightdm-webkit2-greeter.conf was pointing to `/home/korny/myImage.png` which was said to not be readable by lightdm-webkit2-greeter
