### ISSUE TITLE
Encoundered error after update

### ISSUE THREAD

**Issue by mushi-nova** [manilarome/the-glorious-lightdm-webkit2-theme#27]
Recently I downloaded the latest git repository but I continuously get `An error was detected in the current theme that could interfere with the system login process`. 
To know more about the error I ran `lightdm-webkit2-greeter` and I got the following error 
```
file:///usr/share/lightdm-webkit/themes/glorious/js/sessions.js:35:27: CONSOLE ERROR TypeError: undefined is not an object (evaluating 'this._sessionsObject[0].key')
```
I tried to install through AUR as well as through `git clone` but for both cases I get similar error. I would be really glad if anyone can help me out with this

**Comment by eromatiya** [comment]
The first session object is missing. It means the theme doesn't detect any environment. Do you have a DE/WM installed?

**Comment by mushi-nova** [comment]
Yes I do. I'm running AwesomeWM. It happened just today all of a sudden but yesterday it was absolutely fine

**Comment by eromatiya** [comment]
Weird... After running the webkit-greeter from terminal, inspect element, go to console, clear the localStorage by `localStorage.clear();`

**Comment by mushi-nova** [comment]
Ohh sorry to bother. Actually it was my mistake since I tried to change `/usr/share/xsessions/awesome.desktop` entry. And that messed up everything. It's all my fault
