### ISSUE TITLE
An error was detected in the current theme

### ISSUE THREAD

**Issue by CyberManifest** [manilarome/the-glorious-lightdm-webkit2-theme#32]
Following a guide from here: https://youtu.be/oQ8RWtD3MTQ?t=1031
I was attempting to install the lightdm-webkit2-theme-glorious but encounter the error:
`An error was detected in the current theme that could interfere with the system login process `... similar to looking like this:
![epps75d0zwu41](https://user-images.githubusercontent.com/22405699/94245179-8160fa80-fedf-11ea-8b89-0c04308d9748.jpg)
Looking over https://github.com/manilarome/lightdm-webkit2-theme-glorious and seeing the mention of the race condition, I attempted to enable debug mode, upon reboot I still get the dialog and am not able to right click until I select "Load Default Theme" (I also seem to have to make the same selection multiple times before it will allow me to continue on) after selecting "Load Default Theme" I'm able to right click and choose "reload" but it's still not the glorious theme.

**Comment by eromatiya** [comment]
>  but it's still not the glorious theme.

What do you mean by this? Even if there's an error it should already be the glorious theme.

> Following a guide from here: https://youtu.be/oQ8RWtD3MTQ?t=1031

Wow Linux Scoop used my theme in their video? Damn lol. Anyway, Linux Scoop uses an old installation method. The `webkit_theme` should now be `glorious` instead of `lightdm-webkit2-theme-glorious`. So yeah. You should read [this part](https://github.com/manilarome/lightdm-webkit2-theme-glorious#installation) of the README. Closing this now! Thanks for reporting!

**Comment by CyberManifest** [comment]
> What do you mean by this? Even if there's an error it should already be the glorious theme.

Well, I don't know if it's the glorious theme, cause I can't actually use it because of the error dialog box, that forces me to use the default theme instead. Also, it doesn't look anything like the video.

> Wow Linux Scoop used my theme in their video? Damn lol. Anyway, Linux Scoop uses an old installation method.

It may be an old installation method, but the video was uploaded only a few weeks ago and it seemed to be working for them.

> The webkit_theme should now be glorious instead of lightdm-webkit2-theme-glorious. 

What do you mean by this? Like the package name, the reference in the config file? Because if you mean in the config file that was what was set just as it was in the video. And per your... 
>So yeah. You should read [this part](https://github.com/manilarome/lightdm-webkit2-theme-glorious#installation) of the README.

It says... and I quote: 

"`$ yay -Syu lightdm-webkit2-theme-glorious`"

not "glorious"

**Comment by eromatiya** [comment]
> Well, I don't know if it's the glorious theme, cause I can't actually use it because of the error dialog box,

You can press cancel to see the current broken theme. If it's black screen then lightdm can't detect the theme you set.

> What do you mean by this? Like the package name, the reference in the config file? Because if you mean in the config file that was what was set just as it was in the video. And per your...

Yes the package name is ` lightdm-webkit2-theme-glorious` but the **theme name** is `glorious`.

> It may be an old installation method, but the video was uploaded only a few weeks ago and it seemed to be working for them.

I watched it and they set the `webkit_theme` to `lightdm-webkit2-theme-glorious`. Again, it should be `glorious`. (Believe in me, i'm the dev lol).

The version that they've used is v1.0.X, while the version in this repo is already v2.0.x.

**Comment by CyberManifest** [comment]
> I watched it and they set the webkit_theme to lightdm-webkit2-theme-glorious. Again, it should be glorious. (Believe in me, i'm the dev lol).

Do you have a time stamp link of where in the video?

> The version that they've used is v1.0.X, while the version in this repo is already v2.0.x.

There is only one "glorious" package in the AUR and it's the one I have installed.

> You can press cancel to see the current broken theme. If it's black screen then lightdm can't detect the theme you set.

Maybe this will help, this is what I have set and configured on my system... show me where I'm doing wrong....

![Screenshot from 2020-09-25 06 05 52](https://user-images.githubusercontent.com/22405699/94260575-0951ff00-fef6-11ea-9654-defb5fc113d7.png)
![Screenshot from 2020-09-25 06 15 35](https://user-images.githubusercontent.com/22405699/94260919-9bf29e00-fef6-11ea-8b64-c270e86e30c9.png)
![Screenshot from 2020-09-25 06 15 15](https://user-images.githubusercontent.com/22405699/94260931-9f862500-fef6-11ea-87b5-94510dd2d05a.png)

**Comment by CyberManifest** [comment]
Here is what I get on a fresh reboot...
![IMG_0183](https://user-images.githubusercontent.com/22405699/94261691-e7597c00-fef7-11ea-93ce-7ea1eb3fac32.jpeg)
![IMG_0181](https://user-images.githubusercontent.com/22405699/94261736-f6402e80-fef7-11ea-948b-ba7287025eee.jpeg)
![IMG_0182](https://user-images.githubusercontent.com/22405699/94261757-ff310000-fef7-11ea-92e9-e22b74f492fc.jpeg)

Here is what I get when I press [esc]

![IMG_0185](https://user-images.githubusercontent.com/22405699/94261802-140d9380-fef8-11ea-80e5-b66cf84105bf.jpeg)
![IMG_0184](https://user-images.githubusercontent.com/22405699/94261811-1a037480-fef8-11ea-9bdc-94dbd8c82fe3.jpeg)

**Comment by eromatiya** [comment]
> Do you have a time stamp link of where in the video?

It's not needed. I got mixed up `lightdm-webkit2-greeter.conf` and `lightdm.conf`. Pardon my ignorance earlier. Linux Scoop indeed set `webkit_theme` to `glorious` in `lightdm-webkit2-greeter.conf`.

> Here is what I get when I press [esc]

Please, press the cancel button because escape defaults to `Load default theme`, iirc.

Anyway you can debug it by running `lightdm-webkit2-greeter` in your terminal.

**Comment by CyberManifest** [comment]
> Please, press the cancel button because escape defaults to Load default theme, iirc.

Pressing cancel does nothing for me, the dialog remains. (Although I think I remember pressing cancel multiple times after getting to default theme and it finally going away) And pressing escape defaults to "Fall back theme" for me.

> Anyway you can debug it by running lightdm-webkit2-greeter in your terminal.

I'll test this and see what I come up with.

**Comment by CyberManifest** [comment]
Now we're getting somewhere...

![Screenshot from 2020-09-25 07 53 15](https://user-images.githubusercontent.com/22405699/94269480-563cd200-ff04-11ea-9568-9f307b0006bf.jpeg)
![Screenshot from 2020-09-25 07 52 20](https://user-images.githubusercontent.com/22405699/94269492-59d05900-ff04-11ea-9ffb-fd5bff233e83.jpeg)

**Comment by eromatiya** [comment]
Now I know what's causing the problem. It's the Credits file in your backgrounds directory. Try to delete, like `rm` it to oblivion lol. Lightdm webkit2 has a limitation, it cannot detect if the file format/extension that's why it cannot exclude it. Hence the "error opening directory" error. It's already in the [README](https://github.com/manilarome/lightdm-webkit2-theme-glorious#notes). But yeah, it is something that can be easily overlooked.

**Comment by CyberManifest** [comment]
> Now I know what's causing the problem. It's the Credits file in your backgrounds directory. Try to delete, like rm it to oblivion lol. Lightdm webkit2 has a limitation, it cannot detect if the file format/extension that's why it cannot exclude it. Hence the "error opening directory" error. It's already in the README. But yeah, it is something that can be easily overlooked.

Yeah, I removed them, I'm also uninstalling the mint backgrounds from the AUR just to be double safe. Testing now... Thank You ;-)

**Comment by CyberManifest** [comment]
Update, I can confirm, removing the unknown file formats seems to have resolved the dialog box issue. But now what to do with these...

![Screenshot from 2020-09-25 08 07 52](https://user-images.githubusercontent.com/22405699/94270901-72417300-ff06-11ea-91c1-93da12eca192.jpeg)

**Comment by eromatiya** [comment]
Those are just a bunch of logs. Don't worry about them. Try to login again, it should work now without a problem.

**Comment by CyberManifest** [comment]
> Those are just a bunch of logs. Don't worry about them. Try to login again, it should work now without a problem.

Great, Works fine now! Thank You...
Marking this issue resolved and closed.

P.S. Final Product:

![Screenshot from 2020-09-25 08 13 49](https://user-images.githubusercontent.com/22405699/94271542-66a27c00-ff07-11ea-9bef-21eb4a3f83ca.jpeg)

**Comment by surfaceflinger** [comment]
If someone else has this error and there is no output in logs:
`chmod -R 755 /usr/share/lightdm-webkit/themes/glorious`
I wasted 1 hour "fixing" because I messed up permissions during installation 😊

**Comment by jakiisheep** [comment]
I tried everything in here and nothing works :(

**Comment by IEdiong** [comment]
Hello @manilarome, I'm having the same issue but my log for `lightdm-webkit2-greeter` is different. Please take a look.
![lightdm-webkit2-greeter-error](https://user-images.githubusercontent.com/81180771/136775202-9e565bda-7cf2-450a-82f6-1df521c867c9.png)
![lightdm-webkit2-greeter-errorScreen](https://user-images.githubusercontent.com/81180771/136775462-29524848-730e-4598-97da-9c7f464edc77.png)

**Comment by IEdiong** [comment]
> Hello @manilarome, I'm having the same issue but my log for `lightdm-webkit2-greeter` is different. Please take a look.
![neofetch-pc](https://user-images.githubusercontent.com/81180771/136777515-455f428e-9308-4b4e-b7e8-d0562a09778d.png)

**Comment by Cheeseboy8020** [comment]
[+0.00s] DEBUG: Logging to /var/log/lightdm/lightdm.log
[+0.00s] DEBUG: Starting Light Display Manager 1.30.0, UID=0 PID=16173
[+0.00s] DEBUG: Loading configuration dirs from /usr/share/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration dirs from /usr/local/share/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration dirs from /etc/xdg/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration from /etc/lightdm/lightdm.conf
[+0.00s] DEBUG: Using Xephyr for X servers
[+0.00s] DEBUG: Registered seat module local
[+0.00s] DEBUG: Registered seat module xremote
[+0.00s] DEBUG: Using D-Bus name org.freedesktop.DisplayManager
[+0.00s] DEBUG: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ?gio-vfs?
[+0.01s] DEBUG: Monitoring logind for seats
[+0.01s] DEBUG: New seat added from logind: seat0
[+0.01s] DEBUG: Seat seat0: Loading properties from config section Seat:*
[+0.01s] DEBUG: Seat seat0 has property CanMultiSession=no
[+0.01s] DEBUG: Seat seat0: Starting
[+0.01s] DEBUG: Seat seat0: Creating greeter session
[+0.01s] DEBUG: Seat seat0: Creating display server of type x
[+0.01s] DEBUG: Could not run plymouth --ping: Failed to execute child process ?plymouth? (No such file or directory)
[+0.01s] DEBUG: Using VT 7
[+0.01s] DEBUG: Seat seat0: Starting local X display on VT 7
[+0.01s] DEBUG: XServer 1: Logging to /var/log/lightdm/x-1.log
[+0.01s] DEBUG: XServer 1: Writing X server authority to /run/lightdm/root/:1
[+0.01s] DEBUG: XServer 1: Launching X Server
[+0.01s] DEBUG: Launching process 16178: /usr/bin/Xephyr :1 -seat seat0 -auth /run/lightdm/root/:1 -nolisten tcp vt7 -novtswitch
[+0.01s] DEBUG: XServer 1: Waiting for ready signal from X server :1
[+0.01s] DEBUG: Acquired bus name org.freedesktop.DisplayManager
[+0.01s] DEBUG: Registering seat with bus path /org/freedesktop/DisplayManager/Seat0
[+0.01s] DEBUG: Loading users from org.freedesktop.Accounts
[+0.01s] DEBUG: User /org/freedesktop/Accounts/User1000 added
Failed to use bus name org.freedesktop.DisplayManager, do you have appropriate permissions?

**Comment by anjosyula** [comment]
I have same issue
![image](https://user-images.githubusercontent.com/68305035/147684144-183d7fa1-95e1-44a5-9afd-b4792f619f70.png)
![image](https://user-images.githubusercontent.com/68305035/147685677-7cc76c3b-a8ff-44a4-b212-37997f3ec1b6.png)

**Comment by ghost** [comment]
> I have same issue ![image](https://user-images.githubusercontent.com/68305035/147684144-183d7fa1-95e1-44a5-9afd-b4792f619f70.png) ![image](https://user-images.githubusercontent.com/68305035/147685677-7cc76c3b-a8ff-44a4-b212-37997f3ec1b6.png)

I'm having the exact same logs

Is there a fix?

**Comment by meisme-dev** [comment]
Reinstalling it using `yay -S lightdm-webkit2-theme-glorious --overwrite "*"` fixed it for me.

**Comment by ronylee11** [comment]
hi, how can i disable the error popup entirely? the theme works great for me, just gets kinda annoying having to press cancel everytime i reboot
debugging with lightdm-webkit2-greeter does not have that popup tho
tried searching in 
/usr/share/backgrounds/
/usr/share/pixmaps/
but i only find files with .svg, .png, and .jpg extensions, can u specify the exact path for the Credits file? ( cant recall if i removed it months ago)
i also removed
/usr/share/licenses/lightdm-webkit2-theme-glorious/LICENSE
/usr/share/lightdm-webkit/themes/glorious/LICENSE
but the annoying popup still occurs

**Comment by nkahne** [comment]
![greeter_error](https://user-images.githubusercontent.com/57449313/180655805-dc0ce533-9acc-48c0-89e2-324a73e41490.png)

I get similar errors. Something seems to be up with the vars.js file?
I have only picture-like files in usr/share/backgrounds, so that can't be it.

**Comment by sharpicx** [comment]
> Reinstalling it using `yay -S lightdm-webkit2-theme-glorious --overwrite "*"` fixed it for me.

it still doesnt work, how can i solve this?
