### ISSUE TITLE
Modify authentication messages

### ISSUE THREAD

**Issue by CyberManifest** [manilarome/the-glorious-lightdm-webkit2-theme#33]
Didn't know any other way to contact...

What's with the authentication messages?
Can I remove some or add a few of my own without modifying too much code? (Is the number of them set / required?)

P.S. Sorry for the bother.

**Comment by eromatiya** [comment]
You can find them here https://github.com/manilarome/lightdm-webkit2-theme-glorious/blob/bbc63b681ec42751199dcadab2df78bbdafed519/js/authenticate.js#L12-L42

**Comment by Morphy-Kun** [comment]
Bruh! This is totally my kinda humour XD
![image](https://user-images.githubusercontent.com/44739457/109203302-cf976400-77c5-11eb-8f1c-acd9d0bfcfdf.png)

**Comment by Morphy-Kun** [comment]
I'm enjoying it way more than I should ( U w U )/

![image](https://user-images.githubusercontent.com/44739457/109207569-189de700-77cb-11eb-8050-3d754e2bf420.png)
