### ISSUE TITLE
Profile Picture Not Updating

### ISSUE THREAD

**Issue by jacksonSingleton** [manilarome/the-glorious-lightdm-webkit2-theme#35]
I used a ~/.face file and updated accountservices info. Can't seem to get my avatar off of the default avatar image. Any help would be greatly appreciated. Also tried mugshot to no avail. I'm using Arch with bspwm if that's of any significance.

**Comment by jacksonSingleton** [comment]
Also, I followed the similar issues' solutions with no luck.

**Comment by jacksonSingleton** [comment]
Checked other themes and avatar is being correctly loaded gonna make a PR and see if I can't get it to work.

**Comment by eromatiya** [comment]
Please check the logs. Run it first from a terminal emulator, it should spit out some logs.

**Comment by jacksonSingleton** [comment]
For some reason the default account settings were screwed up. I added some code on accounts.js to specifically default to lightdm.users[0], and after that the defaults were properly updated and it fixed the issue. I know it's not a great solution but it worked for me.
