### ISSUE TITLE
Is it possible to delay logging in after successful authentication?

### ISSUE THREAD

**Issue by Morphy-Kun** [manilarome/the-glorious-lightdm-webkit2-theme#60]
Hey, I was wondering if there was an option to delay logging in the user after successful authentication? My reason for asking is that I like changing the default authentication messages and I would like it if there was a slight delay so I can actually read the messages.
 
![image](https://user-images.githubusercontent.com/44739457/127093645-7e3ba115-70c7-4390-af70-365c1b8c935b.png)

**Comment by JezerM** [comment]
Check [here](https://github.com/manilarome/lightdm-webkit2-theme-glorious/blob/cafa66415fe40bb6f2ab8f7e78efda4315708913/js/authenticate.js#L62~L79). Change the **loginFade** and **start_session** timeout to your requirements.

**Comment by Morphy-Kun** [comment]
Thanks a lot mate. ( ^ u ^ )b
