### ISSUE TITLE
~/.face and /var/lib/AccountsService/icons/$(whoami) not working properly

### ISSUE THREAD

**Issue by markus-wa** [manilarome/the-glorious-lightdm-webkit2-theme#65]
Hey, thanks for making this amazing theme!

I've set up these two files via `mugshot` - when running `lightdm-webkit2-greeter` from the terminal the image is displayed correctly, but at startup it's not displayed.

Strangely however when I go to the settings section in the top right it's there - just not on the main splash screen.

From the terminal it also displays my full name as configured via mugshot rather than just my username.

![image](https://user-images.githubusercontent.com/5138316/145913169-9ae8bbb6-1573-4478-9396-7c287b554031.png)

```
$ file /var/lib/AccountsService/icons/$(whoami)
/var/lib/AccountsService/icons/mark: PNG image data, 250 x 250, 8-bit/color RGB, non-interlaced

$ file ~/.face
/home/mark/.face: PNG image data, 250 x 250, 8-bit/color RGB, non-interlaced

```

any idea what this might be?

permissions on both files are 644

**Comment by lanbosandershi** [comment]
Same issue here, it seems to be only showing the image in the toolbar.

**Comment by NonoTheLion** [comment]
You can try to change the _user.svg_ default file (in your **/usr/share/lightdm-webkit/themes/glorious/assets/profiles/**) by your own svg file. It's a trash solution, but it worked for me.

**Comment by 23prime** [comment]
I found information at [Pull Request #50](https://github.com/manilarome/lightdm-webkit2-theme-glorious/pull/50).

```md
**Note:** If the avatar does not change when you put the file in the folder, just go to the users section select another user (or the same user) and the change will appear.
```

I used to have the same issue, but I tried this and solved.

**Comment by markus-wa** [comment]
I think it might have been a file format issue for me. it's resolved now anyway
